kind: pipeline
type: docker
name: production

trigger:
  branch:
  - main
  event:
  - push

steps:
  - name: set-prod-tag-from-package
    image: node:20
    commands:
      - cd api
      - echo -n "latest,$(npm pkg get version | sed 's/"//g')" > ../.tags

  - name: build docker-image
    image: plugins/docker
    pull: always
    settings:
      registry: docker-regis.iex.ec
      repo: docker-regis.iex.ec/iexec-iapp-api
      context: ./api
      dockerfile: api/Dockerfile
      username:
        from_secret: nexus-user
      password:
        from_secret: nexus-password

  - name: deploy to production
    image: appleboy/drone-ssh
    pull: always
    environment:
      DOCKER_USERNAME:
        from_secret: nexus-user
      DOCKER_PASSWORD:
        from_secret: nexus-password
    settings:
      host:
        from_secret: production-iapp-api-host
      username:
        from_secret: ssh-iapp-api-user
      key:
        from_secret: ssh-iapp-api-key
      port: 22
      envs:
        - DOCKER_USERNAME
        - DOCKER_PASSWORD
      script:
        - cd /opt/iapp-api
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD docker-regis.iex.ec
        - docker compose pull
        - docker compose down --remove-orphans
        - sleep 5
        - docker compose up -d
        - docker logout docker-regis.iex.ec
