name: API deploy rollback
description: Rollback the API deployment to a previous version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Tag to rollback to'
        required: true
        type: string
      logLevel:
        description: 'Log level for the deployment'
        default: info
        type: choice
        options:
          - trace
          - debug
          - info
          - warn
          - error

jobs:
  deploy:
    if: ${{ github.ref_name == 'main' }}
    uses: ./.github/workflows/reusable-api-deploy.yml
    with:
      tag: ${{ inputs.version }}
      logLevel: ${{ inputs.logLevel }}
    secrets:
      host: ${{ secrets.API_HOST }}
