name: CLI npm publish latest
description: Publish iapp CLI on npm when a release is published

on:
  release:
    types: [published]

jobs:
  npm-publish:
    # only run for releases with tag 'iapp-v*' as created by release-please for CLI
    if: startsWith(github.ref_name,'iapp-v')
    uses: ./.github/workflows/reusable-cli-npm.yml
    with:
      tag: 'latest'
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
