name: CLI npm publish staging
description: Publish a staging version of iapp CLI on npm

on:
  workflow_dispatch:

jobs:
  compute-staging-version:
    uses: ./.github/workflows/reusable-compute-staging-version.yml
    with:
      working-directory: cli

  npm-publish:
    uses: ./.github/workflows/reusable-cli-npm.yml
    needs: compute-staging-version
    with:
      version: ${{ needs.compute-staging-version.outputs.version }}
      tag: ${{ needs.compute-staging-version.outputs.dist-tag }}
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
